packages:
  - packages/**
  - apps/**
catalog:
  '@antfu/eslint-config': ^4.10.1
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.28.1
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@rollup/plugin-commonjs': ^28.0.3
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-node-resolve': ^16.0.1
  '@types/fs-extra': ^11.0.4
  '@types/js-yaml': ^4.0.9
  '@types/markdown-it': ^14.1.2
  '@types/node': ^22.13.10
  ajv: ^8.17.1
  art-template: ^4.13.4
  chokidar: ^4.0.3
  commitizen: ^4.3.1
  cz-git: ^1.11.1
  esbuild: ^0.25.1
  eslint: ^9.23.0
  fs-extra: ^11.3.0
  js-yaml: ^4.1.0
  json-schema-to-ts: ^3.1.1
  markdown-it: ^14.1.0
  markdown-it-github-alerts: ^0.3.1
  read-pkg: ^9.0.1
  remark: ^15.0.1
  remark-frontmatter: ^5.0.0
  remark-remove-comments: ^1.1.1
  rimraf: ^6.0.1
  rollup: ^4.37.0
  rollup-plugin-dts: ^6.2.1
  rollup-plugin-esbuild: ^6.2.1
  simple-git-hooks: ^2.11.1
  unist-util-visit: ^5.0.0
  vite: ^6.2.2
  vite-node: ^3.0.9
  vitepress: ^1.6.3
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
