name: Build README

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install
        run: npm install

      - name: Build README
        run: npm run build

      - name: Push README.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: :memo: 更新 README.md'
