name: Spider README

on:
  workflow_dispatch:
  schedule:
    # 每周一 0 点
    - cron: '0 0 * * 1'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install
        run: npm install

      - name: Spider README
        env:
          VITE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run spider

      - name: Push dist
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: :rewind: 抓取 README.md'
          file_pattern: dist